export const categories = [
    "All",
    "Antiques",
    "Art",
    "Books",
    "Cameras & Photo",
    "Cell Phones & Accessories",
    "Clothing & Shoes",
    "Computers & Tablets",
    "DVDs & Movies",
    "Gift Cards",
    "Health & Beauty",
    "Sports",
    "Video Games",
];
